apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: koios-namespace
spec:
  selector:
    app: database
  type: NodePort
  ports:
    - name: web-port
      port: 3306
      targetPort: 3306
