apiVersion: StorageClass
kind: storage.k8s.io/v1beta1
metadata:
  name: database-sv
provisioner: kuberntes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db"
  io_priority: "high"
  fs: "xfs"
