apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: koios-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: docker.io/library/mysql:latest
        imagePullPolicy: IfNotPresent
        ports:
        -  containerPort: 3306
