apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: koios-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend
        imagePullPolicy: IfNotPresent
        ports:
        -  containerPort: 8080
